PREFIX mer: <https://seanchatmangpt.github.io/ontology/mermaid#>
SELECT ?type ?missing WHERE {
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:pythonInternalId ?x} BIND("pythonInternalId" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:pythonModelClass ?x} BIND("pythonModelClass" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:pythonTransformerClass ?x} BIND("pythonTransformerClass" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:pythonRenderFunction ?x} BIND("pythonRenderFunction" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:grammarFile ?x} BIND("grammarFile" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:detectPattern ?x} BIND("detectPattern" AS ?missing)} UNION
 { ?type a mer:DiagramType; mer:pythonSupport true. FILTER NOT EXISTS {?type mer:renderStrategy ?x} BIND("renderStrategy" AS ?missing)}
}
