PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:ontology dct:title "mmdio PaaS manufacturing ontology" . } BIND("ONTOLOGY_TITLE" AS ?violation) }
