PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:service a dcat:DataService . } BIND("SERVICE_TYPE" AS ?violation) }
