PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:service dct:conformsTo <https://jsonapi.org/format/> . } BIND("SERVICE_JSONAPI_CONFORMANCE" AS ?violation) }
