PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:service paas:contentType "text/plain" . } BIND("SERVICE_PLAIN_CONTENT_TYPE" AS ?violation) }
