PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:RenderIntent a owl:Class . } BIND("RENDER_INTENT_CLASS" AS ?violation) }
