PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:RenderActivity rdfs:subClassOf prov:Activity . } BIND("RENDER_ACTIVITY_PROV_ACTIVITY" AS ?violation) }
