PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:RenderReceipt skos:prefLabel "Render receipt" . } BIND("RENDER_RECEIPT_LABEL" AS ?violation) }
