PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:standing rdfs:subPropertyOf skos:notation . } BIND("STANDING_NOTATION" AS ?violation) }
