PREFIX paas: <https://seanchatmangpt.github.io/ontology/mmdio/paas#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?violation WHERE { FILTER NOT EXISTS { paas:receiptDigest a rdf:Property . } BIND("RECEIPT_DIGEST_PROPERTY" AS ?violation) }
