_commit: v2.0.0
_src_path: gh:superlinear-ai/substrate
author_email: info@chatmangpt.com
author_name: Sean Chatman
project_description: Mermaid Diagrams as Universal IO
project_name: mmdio
project_type: app
project_url: https://github.com/seanchatmangpt/mmdio
python_version: '3.13'
typing: strict
with_conventional_commits: true
with_fastapi_api: true
with_typer_cli: true
