"""Registry of all 10 domain scenarios."""

from __future__ import annotations

from ocelgen.scenarios.domain import DomainScenario

SCENARIO_REGISTRY: dict[str, DomainScenario] = {
    "customer-support-triage": DomainScenario(
        name="customer-support-triage",
        description="Customer support ticket triage: classify, research, and draft response",
        pattern="sequential",
        runs=50,
        noise=0.20,
        seed=1001,
        user_queries=[
            "My refund for order #4821 hasn't arrived after 10 business days",
            "I was charged twice for my Pro subscription this month",
            "The delivery tracking says 'delivered' but I never received my package",
            "I can't log into my account after the password reset",
            "My discount code SAVE20 isn't working at checkout",
            "I need to cancel my order but the cancel button is greyed out",
            "The product I received doesn't match the listing photos at all",
            "My gift card balance disappeared after a failed transaction",
            "I've been waiting 3 weeks for a replacement item that was promised in 5 days",
            "The app keeps crashing when I try to view my order history",
            "I was promised free shipping but got charged $12.99",
            "My subscription renewed even though I cancelled it last month",
        ],
        agent_personas={
            "researcher": "You are a support agent researching the customer's issue in the knowledge base and order management system",
            "analyst": "You are a support analyst determining the root cause, checking policies, and deciding the appropriate resolution",
            "summarizer": "You are a support agent drafting a clear, empathetic response to the customer with the resolution",
        },
        tool_descriptions={
            "web_search": "Search the internal knowledge base for policies, FAQs, and troubleshooting guides",
            "file_reader": "Read customer account details, order history, and previous support interactions",
            "calculator": "Calculate refund amounts, shipping costs, or discount values",
            "code_interpreter": "Run queries against the order management database",
        },
    ),
    "code-review-pipeline": DomainScenario(
        name="code-review-pipeline",
        description="Automated code review: supervisor delegates to linter, security reviewer, and style checker",
        pattern="supervisor",
        runs=50,
        noise=0.20,
        seed=2002,
        user_queries=[
            "Review PR #342: Add user authentication middleware with JWT tokens",
            "Review PR #343: Refactor database connection pooling for PostgreSQL",
            "Review PR #344: Add rate limiting to public API endpoints",
            "Review PR #345: Migrate from REST to GraphQL for the user profile service",
            "Review PR #346: Fix SQL injection vulnerability in search endpoint",
            "Review PR #347: Add WebSocket support for real-time notifications",
            "Review PR #348: Implement RBAC authorization for admin panel",
            "Review PR #349: Optimize image upload pipeline with async processing",
            "Review PR #350: Add OpenTelemetry instrumentation to all HTTP handlers",
            "Review PR #351: Replace homegrown cache with Redis for session storage",
            "Review PR #352: Add CORS configuration for multi-tenant SaaS deployment",
            "Review PR #353: Implement graceful shutdown handling for background workers",
        ],
        agent_personas={
            "supervisor": "You are a senior engineering lead triaging a pull request and delegating review tasks to specialized reviewers",
            "researcher": "You are a code linter checking for bugs, type errors, unused imports, and code smells",
            "coder": "You are a security reviewer scanning for vulnerabilities: injection, XSS, auth bypasses, secrets in code",
            "reviewer": "You are a style checker verifying naming conventions, documentation, test coverage, and architectural consistency",
        },
        tool_descriptions={
            "web_search": "Search documentation for language/framework best practices",
            "file_reader": "Read the pull request diff, source files, and test files",
            "code_interpreter": "Run static analysis tools (ruff, mypy, bandit) on the changed files",
        },
    ),
    "market-research": DomainScenario(
        name="market-research",
        description="Market research: fan-out to competitor analyst, trend researcher, and report writer",
        pattern="parallel",
        runs=50,
        noise=0.20,
        seed=3003,
        user_queries=[
            "Analyze the competitive landscape for AI code assistants in 2025",
            "Research market trends in open-source large language model deployment",
            "Compare pricing strategies of major cloud GPU providers",
            "Investigate the enterprise adoption rate of retrieval-augmented generation",
            "Analyze the developer tools market with focus on observability platforms",
            "Research the growth trajectory of AI-powered customer support solutions",
            "Compare feature sets of top 5 vector database providers",
            "Investigate market opportunities in AI agent orchestration frameworks",
            "Analyze competitive positioning of major MLOps platforms",
            "Research enterprise spending trends on generative AI infrastructure",
            "Compare go-to-market strategies of AI coding startups vs incumbents",
            "Investigate the impact of open-weight models on commercial AI services",
        ],
        agent_personas={
            "planner": "You are a research director breaking down the research question into parallel workstreams for your team",
            "researcher": "You are a competitive intelligence analyst gathering data on market players, products, and positioning",
            "analyst": "You are a market trends analyst identifying growth patterns, adoption curves, and emerging opportunities",
            "writer": "You are a research report writer synthesizing findings into clear, data-backed narratives",
            "aggregator": "You are a research director combining all workstreams into a cohesive final market research report",
        },
        tool_descriptions={
            "web_search": "Search for press releases, analyst reports, funding announcements, and product launches",
            "calculator": "Calculate market share percentages, growth rates, and financial comparisons",
            "database_query": "Query internal market intelligence database for historical data",
            "text_splitter": "Split long documents and reports into sections for focused analysis",
        },
    ),
    "legal-document-analysis": DomainScenario(
        name="legal-document-analysis",
        description="Legal document analysis: extract clauses, check compliance, summarize risks",
        pattern="sequential",
        runs=50,
        noise=0.15,
        seed=4004,
        user_queries=[
            "Review this SaaS vendor agreement for data processing compliance with GDPR",
            "Analyze the indemnification clauses in the proposed partnership agreement",
            "Check this employment contract template against California labor law requirements",
            "Review the liability limitations in our cloud services terms of service",
            "Analyze the intellectual property assignment clauses in this contractor agreement",
            "Check the termination and renewal provisions in the enterprise license agreement",
            "Review the data breach notification requirements in this DPA addendum",
            "Analyze the non-compete and non-solicitation scope in the executive agreement",
            "Check the force majeure clause coverage in our supply chain contracts",
            "Review the warranty disclaimers in the open-source license for commercial use",
            "Analyze the audit rights and compliance reporting in the SOC 2 vendor agreement",
            "Check the cross-border data transfer mechanisms in the international DPA",
        ],
        agent_personas={
            "researcher": "You are a legal analyst extracting and cataloging key clauses, definitions, and obligations from the document",
            "analyst": "You are a compliance specialist checking extracted clauses against applicable regulations and internal policies",
            "summarizer": "You are a legal advisor summarizing the risk exposure and recommending actions for the business team",
        },
        tool_descriptions={
            "web_search": "Search legal databases for relevant case law, regulatory guidance, and compliance standards",
            "file_reader": "Read the contract document, internal policy templates, and compliance checklists",
            "calculator": "Calculate financial exposure, liability caps, and penalty thresholds",
            "code_interpreter": "Run clause comparison against standard template library",
        },
    ),
    "data-pipeline-debugging": DomainScenario(
        name="data-pipeline-debugging",
        description="Data pipeline debugging: supervisor routes to log analyzer, schema checker, and fix proposer",
        pattern="supervisor",
        runs=50,
        noise=0.25,
        seed=5005,
        user_queries=[
            "Pipeline job etl_daily_users failed at 03:42 UTC with OOM error on the join stage",
            "Data quality alert: 40% null values in user_email column after last ETL run",
            "Spark job for revenue aggregation has been running 3x longer than usual since Tuesday",
            "Schema mismatch error: upstream API changed the 'address' field from string to object",
            "Duplicate records detected in the orders fact table after backfill job ran twice",
            "Airflow DAG customer_360 stuck in 'running' state for 6 hours with no progress",
            "BigQuery costs spiked 400% this week — investigate which queries are responsible",
            "CDC replication from PostgreSQL to Snowflake has a 4-hour lag since the table alter",
            "Data freshness SLA breach: dashboard data is 8 hours stale instead of 1 hour",
            "dbt model staging_payments failing with 'relation does not exist' after warehouse migration",
            "Partition skew in the daily clickstream job causing executor timeouts on node 3",
            "Kafka consumer group for events_ingest has been rebalancing every 5 minutes since deploy",
        ],
        agent_personas={
            "supervisor": "You are a data engineering lead triaging a pipeline incident and assigning investigation tasks to specialists",
            "researcher": "You are a log analyst examining execution logs, error traces, and resource utilization metrics",
            "coder": "You are a schema and data quality checker validating data shapes, types, and integrity constraints",
            "reviewer": "You are a fix proposer suggesting configuration changes, code patches, or architectural improvements",
        },
        tool_descriptions={
            "web_search": "Search internal runbooks and documentation for known issues and fixes",
            "file_reader": "Read pipeline configuration files, DAG definitions, and dbt models",
            "code_interpreter": "Run diagnostic queries against the data warehouse and metadata store",
            "database_query": "Query pipeline execution logs and monitoring metrics",
        },
    ),
    "content-generation": DomainScenario(
        name="content-generation",
        description="Content generation: fan-out to researcher, writer, and editor with final aggregation",
        pattern="parallel",
        runs=50,
        noise=0.20,
        seed=6006,
        user_queries=[
            "Write a technical blog post about implementing RAG with open-source models",
            "Create a product announcement for our new real-time collaboration feature",
            "Write a developer tutorial on building MCP servers in Python",
            "Create a case study about how Company X reduced inference costs by 60%",
            "Write a comparison article: fine-tuning vs RAG vs prompt engineering",
            "Create a newsletter edition covering this month's top open-source AI releases",
            "Write an onboarding guide for new contributors to our open-source project",
            "Create a technical deep-dive on transformer attention mechanism optimizations",
            "Write a year-in-review post summarizing our community growth and milestones",
            "Create a best-practices guide for deploying LLMs in production environments",
            "Write a post explaining how we built our evaluation pipeline for model quality",
            "Create an explainer article on quantization techniques for edge deployment",
        ],
        agent_personas={
            "planner": "You are a content strategist planning the article structure, key points, and audience targeting",
            "researcher": "You are a technical researcher gathering facts, code examples, benchmarks, and references",
            "analyst": "You are a data analyst pulling metrics, usage statistics, and performance benchmarks to support claims",
            "writer": "You are a technical writer crafting the prose with clear explanations and engaging narrative",
            "aggregator": "You are an editor combining research and writing into a polished, publication-ready article",
        },
        tool_descriptions={
            "web_search": "Search for reference materials, documentation, competitor content, and source data",
            "calculator": "Calculate performance metrics, cost comparisons, and statistical summaries",
            "database_query": "Query internal analytics for product usage data and engagement metrics",
            "text_splitter": "Split long reference documents into digestible sections for analysis",
        },
    ),
    "financial-analysis": DomainScenario(
        name="financial-analysis",
        description="Financial analysis: gather filings, compute ratios, write investment memo",
        pattern="sequential",
        runs=50,
        noise=0.20,
        seed=7007,
        user_queries=[
            "Analyze NVIDIA's Q4 2025 earnings and provide an investment recommendation",
            "Compare AMD vs Intel financial performance over the last 4 quarters",
            "Evaluate Snowflake's revenue growth trajectory and path to profitability",
            "Analyze the impact of AI infrastructure spending on Microsoft's cloud margins",
            "Review Palantir's government vs commercial revenue mix and growth sustainability",
            "Assess Datadog's competitive position based on latest financial metrics",
            "Analyze Alphabet's AI investment returns across Cloud and Search segments",
            "Evaluate the financial health of Confluent post their pricing model change",
            "Compare MongoDB vs CockroachDB financial metrics and market positioning",
            "Analyze Meta's Reality Labs spending trajectory and VR market opportunity",
            "Review Salesforce's acquisition integration costs and organic growth rate",
            "Assess the financial impact of open-source strategy on Elastic's revenue",
        ],
        agent_personas={
            "researcher": "You are a financial researcher gathering earnings reports, SEC filings, analyst estimates, and market data",
            "analyst": "You are a financial analyst computing valuation ratios, growth metrics, and peer comparisons",
            "summarizer": "You are an investment analyst writing a concise memo with bull/bear thesis and recommendation",
        },
        tool_descriptions={
            "web_search": "Search SEC EDGAR, earnings transcripts, and financial news for company filings and data",
            "file_reader": "Read downloaded financial statements, spreadsheets, and prior analysis reports",
            "calculator": "Calculate P/E ratios, revenue growth rates, margins, DCF valuations, and peer comparisons",
            "code_interpreter": "Run financial models and generate comparison charts",
        },
    ),
    "incident-response": DomainScenario(
        name="incident-response",
        description="Incident response: on-call supervisor routes to diagnostics, mitigation, and communications agents",
        pattern="supervisor",
        runs=50,
        noise=0.30,
        seed=8008,
        user_queries=[
            "SEV1: API gateway returning 503 for 30% of requests across all regions since 14:22 UTC",
            "SEV2: Authentication service latency spiked to 8s p99, causing login failures",
            "SEV1: Database primary node unresponsive, automatic failover did not trigger",
            "SEV2: CDN cache hit ratio dropped from 95% to 20% after config deploy at 10:15",
            "SEV1: Payment processing completely down — all transactions failing with timeout",
            "SEV2: Memory leak in worker pods causing OOM kills every 45 minutes since release v2.8.1",
            "SEV1: Data loss alert — 2 hours of event data missing from analytics pipeline",
            "SEV2: SSL certificate expired on api.example.com causing all HTTPS connections to fail",
            "SEV1: Kubernetes control plane unresponsive in us-east-1, pods cannot be scheduled",
            "SEV2: Rate limiter misconfigured after deploy — blocking legitimate traffic from top customer",
            "SEV1: DNS propagation failure — 40% of users resolving to old IP after migration",
            "SEV2: Background job queue backed up to 500K messages, consumer throughput dropped 90%",
        ],
        agent_personas={
            "supervisor": "You are the on-call incident commander coordinating the response and making escalation decisions",
            "researcher": "You are a diagnostics engineer investigating logs, metrics, traces, and recent changes to identify root cause",
            "coder": "You are a mitigation engineer implementing hotfixes, rollbacks, or workarounds to restore service",
            "reviewer": "You are a communications specialist drafting status page updates, stakeholder notifications, and post-incident reports",
        },
        tool_descriptions={
            "web_search": "Search internal runbooks, past incident postmortems, and documentation for known solutions",
            "file_reader": "Read deployment manifests, configuration files, and recent git changes",
            "code_interpreter": "Run diagnostic scripts, query monitoring systems, and test fixes",
            "database_query": "Query metrics store (Prometheus/Datadog) and log aggregator (Elasticsearch/Loki)",
        },
    ),
    "academic-paper-review": DomainScenario(
        name="academic-paper-review",
        description="Academic paper review: fan-out to methodology reviewer, novelty assessor, and writing critic",
        pattern="parallel",
        runs=50,
        noise=0.15,
        seed=9009,
        user_queries=[
            "Review: 'Scaling Laws for Sparse Mixture-of-Experts Language Models'",
            "Review: 'Chain-of-Thought Distillation for Efficient Small Language Models'",
            "Review: 'Self-Play Reinforcement Learning for Code Generation Agents'",
            "Review: 'Towards Faithful Long-Context Summarization with Retrieval Augmentation'",
            "Review: 'Dynamic Quantization Strategies for On-Device LLM Inference'",
            "Review: 'Multi-Agent Debate Improves Factual Accuracy in Open-Domain QA'",
            "Review: 'Continual Learning Without Catastrophic Forgetting in Vision-Language Models'",
            "Review: 'Efficient Fine-Tuning of Diffusion Models via Low-Rank Adaptation'",
            "Review: 'Benchmarking Tool-Use Capabilities Across 50 Large Language Models'",
            "Review: 'Constitutional AI: Training Harmless Assistants Without Human Labels'",
            "Review: 'Graph Neural Networks for Molecular Property Prediction at Scale'",
            "Review: 'Multimodal Instruction Following with Interleaved Image-Text Training'",
        ],
        agent_personas={
            "planner": "You are a meta-reviewer assigning the paper to specialist reviewers and defining review criteria",
            "researcher": "You are a methodology reviewer evaluating experimental design, statistical rigor, baselines, and reproducibility",
            "analyst": "You are a novelty assessor comparing the contribution against related work and assessing significance",
            "writer": "You are a writing and clarity critic evaluating presentation quality, figure clarity, and argument structure",
            "aggregator": "You are a meta-reviewer synthesizing all reviews into a final recommendation with accept/revise/reject",
        },
        tool_descriptions={
            "web_search": "Search Semantic Scholar, arXiv, and Google Scholar for related papers and citation context",
            "calculator": "Verify statistical claims, compute effect sizes, and check significance thresholds",
            "database_query": "Query paper metadata database for citation counts and author h-index",
            "text_splitter": "Split the paper into sections (abstract, methods, results, discussion) for focused review",
        },
    ),
    "ecommerce-product-enrichment": DomainScenario(
        name="ecommerce-product-enrichment",
        description="E-commerce product enrichment: scrape specs, normalize attributes, generate descriptions",
        pattern="sequential",
        runs=50,
        noise=0.20,
        seed=10010,
        user_queries=[
            "Enrich product listing: Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
            "Enrich product listing: Apple MacBook Air 15-inch M3 (2024) base configuration",
            "Enrich product listing: Samsung Galaxy S25 Ultra 512GB Titanium Black",
            "Enrich product listing: Dyson V15 Detect Absolute cordless vacuum cleaner",
            "Enrich product listing: LG C4 65-inch OLED evo 4K Smart TV (2024)",
            "Enrich product listing: Bose QuietComfort Ultra Earbuds",
            "Enrich product listing: ASUS ROG Strix G16 gaming laptop RTX 4070",
            "Enrich product listing: Ninja Creami Deluxe ice cream maker NC501",
            "Enrich product listing: Herman Miller Aeron chair fully loaded size B",
            "Enrich product listing: Anker SOLIX F2000 portable power station",
            "Enrich product listing: Kindle Scribe 64GB with Premium Pen",
            "Enrich product listing: DJI Mini 4 Pro drone with RC 2 controller",
        ],
        agent_personas={
            "researcher": "You are a product data specialist scraping manufacturer websites and retail listings for raw specifications",
            "analyst": "You are a data normalizer cleaning, standardizing, and structuring product attributes into a consistent taxonomy",
            "summarizer": "You are a copywriter generating SEO-optimized product descriptions, bullet points, and comparison highlights",
        },
        tool_descriptions={
            "web_search": "Search manufacturer websites, retail listings, and review sites for product specifications",
            "file_reader": "Read existing product catalog entries and attribute taxonomy definitions",
            "calculator": "Convert units, calculate price-per-feature ratios, and normalize numeric specifications",
            "code_interpreter": "Run attribute extraction and normalization scripts on raw product data",
        },
    ),
}


def get_scenario(
    name: str,
    registry: dict[str, DomainScenario] | None = None,
) -> DomainScenario:
    """Look up a domain scenario by name. Raises KeyError if not found."""
    reg = registry if registry is not None else SCENARIO_REGISTRY
    return reg[name]
