"""GENERATED FILE — do not edit by hand. Regenerate with `ggen sync run`.

Public surface of the mmdio engine, projected from packs/mmdio-pack/ontology.ttl.

Previously hand-maintained, which let it drift from the ontology: it imported
ERAttribute/EREntity/StateNode/StateTransition long after those models were renamed to
EntityAttribute/Entity/State/Transition, and nothing caught it because no gate compared
the two. Generating it makes that class of drift unrepresentable.
"""

from __future__ import annotations

from mmdio.engine.models import (
    C4Diagram,
    C4Element,
    C4Relationship,
    ClassDefinition,
    ClassDiagram,
    ClassMember,
    ClassMethod,
    ClassRelationship,
    ERDiagram,
    ERRelationship,
    Entity,
    EntityAttribute,
    FlowchartDiagram,
    FlowchartEdge,
    FlowchartNode,
    GanttChart,
    GanttTask,
    GitBranch,
    GitCommit,
    GitGraph,
    Mindmap,
    MindmapNode,
    PieChart,
    PieSlice,
    SankeyDiagram,
    SankeyFlow,
    SequenceDiagram,
    SequenceMessage,
    SequenceParticipant,
    State,
    StateDiagram,
    Transition,
    MermaidDiagram,
)
from mmdio.engine.enums import (
    C4Level,
    CardinityType,
    MessageType,
    NodeShape,
    ParticipantType,
    RelationshipType,
    TaskStatus,
)
from mmdio.engine.parser import (
    MermaidParser,
    ParsingError,
    parse_mermaid,
    parse_c4,
    parse_class,
    parse_er,
    parse_flowchart,
    parse_gantt,
    parse_git,
    parse_mindmap,
    parse_pie,
    parse_sankey,
    parse_sequence,
    parse_state,
)
from mmdio.engine.render_dispatch import render_diagram, render_model
from mmdio.engine.schemas import schema_for_type
from mmdio.engine.supported import SUPPORTED_TYPES, is_supported
from mmdio.engine.ops import diff, merge, validate_topology

__all__ = [
    "C4Diagram",
    "C4Element",
    "C4Relationship",
    "ClassDefinition",
    "ClassDiagram",
    "ClassMember",
    "ClassMethod",
    "ClassRelationship",
    "ERDiagram",
    "ERRelationship",
    "Entity",
    "EntityAttribute",
    "FlowchartDiagram",
    "FlowchartEdge",
    "FlowchartNode",
    "GanttChart",
    "GanttTask",
    "GitBranch",
    "GitCommit",
    "GitGraph",
    "Mindmap",
    "MindmapNode",
    "PieChart",
    "PieSlice",
    "SankeyDiagram",
    "SankeyFlow",
    "SequenceDiagram",
    "SequenceMessage",
    "SequenceParticipant",
    "State",
    "StateDiagram",
    "Transition",
    "C4Level",
    "CardinityType",
    "MessageType",
    "NodeShape",
    "ParticipantType",
    "RelationshipType",
    "TaskStatus",
    "parse_c4",
    "parse_class",
    "parse_er",
    "parse_flowchart",
    "parse_gantt",
    "parse_git",
    "parse_mindmap",
    "parse_pie",
    "parse_sankey",
    "parse_sequence",
    "parse_state",
    "MermaidDiagram",
    "MermaidParser",
    "ParsingError",
    "SUPPORTED_TYPES",
    "diff",
    "is_supported",
    "merge",
    "parse_mermaid",
    "render_diagram",
    "render_model",
    "schema_for_type",
    "validate_topology",
]
