"""
mmdio.engine: Mermaid diagram parsing, rendering, and operations.

Requires lark>=1.1.0 and pydantic>=2.0.0 (provided by mmdio[all] extra).
"""

from __future__ import annotations

from mmdio.engine.models import (
    C4Diagram,
    C4Element,
    C4Level,
    C4Relationship,
    CardinityType,
    ClassDiagram,
    ClassDefinition,
    ClassMember,
    ClassMethod,
    ClassRelationship,
    ERAttribute as EntityAttribute,
    ERDiagram,
    EREntity as Entity,
    ERRelationship,
    FlowchartDiagram,
    FlowchartEdge,
    FlowchartNode,
    GanttChart,
    GanttTask,
    GitBranch,
    GitCommit,
    GitGraph,
    MermaidDiagram,
    MessageType,
    Mindmap,
    MindmapNode,
    NodeShape,
    ParticipantType,
    PieChart,
    PieSlice,
    RelationshipType,
    SankeyDiagram,
    SankeyFlow,
    SequenceDiagram,
    SequenceMessage,
    SequenceParticipant,
    StateNode as State,
    StateDiagram,
    TaskStatus,
    StateTransition as Transition,
)
from mmdio.engine.parser import (
    parse_c4,
    parse_class,
    parse_er,
    parse_flowchart,
    parse_gantt,
    parse_git,
    parse_mermaid,
    parse_mindmap,
    parse_pie,
    parse_sankey,
    parse_sequence,
    parse_state,
    MermaidParser,
    ParsingError,
)
from mmdio.engine.render import render_diagram
from mmdio.engine.ops import merge, diff, validate_topology

__all__ = [
    # Models
    "MermaidDiagram",
    "FlowchartDiagram",
    "FlowchartNode",
    "FlowchartEdge",
    "SequenceDiagram",
    "SequenceParticipant",
    "SequenceMessage",
    "ClassDiagram",
    "ClassDefinition",
    "ClassMember",
    "ClassMethod",
    "ClassRelationship",
    "StateDiagram",
    "State",
    "Transition",
    "ERDiagram",
    "Entity",
    "EntityAttribute",
    "ERRelationship",
    "GanttChart",
    "GanttTask",
    "PieChart",
    "PieSlice",
    "GitGraph",
    "GitCommit",
    "GitBranch",
    "C4Diagram",
    "C4Element",
    "C4Relationship",
    "Mindmap",
    "MindmapNode",
    "SankeyDiagram",
    "SankeyFlow",
    # Enums
    "NodeShape",
    "MessageType",
    "RelationshipType",
    "CardinityType",
    "TaskStatus",
    "C4Level",
    "ParticipantType",
    # Parser
    "parse_mermaid",
    "parse_flowchart",
    "parse_sequence",
    "parse_class",
    "parse_state",
    "parse_er",
    "parse_gantt",
    "parse_pie",
    "parse_git",
    "parse_c4",
    "parse_mindmap",
    "parse_sankey",
    "MermaidParser",
    "ParsingError",
    # Render
    "render_diagram",
    # Operations
    "merge",
    "diff",
    "validate_topology",
]
