"""RDF provenance registry for Mermaid diagram types.

Pure-Python API for querying diagram type metadata from the RDF registry.
"""

from dataclasses import dataclass
from pathlib import Path

try:
    from rdflib import Graph, Namespace
except ImportError as err:
    msg = "rdflib is required for registry. Install with: pip install -e '.[all]'"
    raise ImportError(msg) from err


@dataclass
class DiagramTypeInfo:
    """Metadata for a supported diagram type."""

    id: str
    displayName: str
    sourceUrl: str
    sourceConfidence: str


@dataclass
class UpstreamSource:
    """Source information for upstream Mermaid release."""

    repo: str
    commit: str
    license: str


# Diagram types implemented in Python.
# Generated by ggen from packs/mmdio-pack/ontology.ttl — see
# src/mmdio/engine/_generated_supported.py.
from ._generated_supported import GENERATED_PYTHON_SUPPORTED

_PYTHON_SUPPORTED = GENERATED_PYTHON_SUPPORTED


def _load_registry() -> tuple[dict[str, DiagramTypeInfo], dict[str, dict]]:
    """Load and parse the RDF registry at module initialization time.

    Returns:
        Tuple of (diagram_types_dict, upstream_sources_dict)
    """
    registry_path = Path(__file__).parent / "registry.ttl"

    graph = Graph()
    graph.parse(registry_path, format="turtle")

    # Define namespaces
    mer = Namespace("https://seanchatmangpt.github.io/ontology/mermaid#")
    dct = Namespace("http://purl.org/dc/terms/")
    prov = Namespace("http://www.w3.org/ns/prov#")

    # Parse upstream release info
    upstream_sources = {}
    for release in graph.subjects(predicate=dct.identifier):
        commit_uri = graph.value(release, prov.value)
        license_uri = graph.value(release, dct.license)
        upstream_sources[str(release)] = {
            "repo": "https://github.com/mermaid-js/mermaid",
            "commit": str(commit_uri) if commit_uri else "",
            "license": str(license_uri) if license_uri else "",
        }

    # Parse diagram types
    diagram_types = {}
    for diagram in graph.subjects(predicate=mer.diagramId):
        diagram_id_literal = graph.value(diagram, mer.diagramId)
        if diagram_id_literal is None:
            continue

        diagram_id = str(diagram_id_literal)
        display_name_literal = graph.value(diagram, mer.displayName)
        display_name = str(display_name_literal) if display_name_literal else diagram_id
        source_url = graph.value(diagram, mer.sourceUrl)
        source_confidence = graph.value(diagram, mer.sourceConfidence)

        diagram_types[diagram_id] = DiagramTypeInfo(
            id=diagram_id,
            displayName=display_name,
            sourceUrl=str(source_url) if source_url else "",
            sourceConfidence=str(source_confidence) if source_confidence else "",
        )

    return diagram_types, upstream_sources


# Cache at module load time
_DIAGRAM_TYPES, _UPSTREAM_SOURCES = _load_registry()


def list_diagram_types() -> list[DiagramTypeInfo]:
    """List all diagram types from the registry.

    Returns:
        List of DiagramTypeInfo objects (39 types total).
    """
    return list(_DIAGRAM_TYPES.values())


def get_upstream_source(diagram_id: str) -> UpstreamSource:
    """Get upstream source information for a diagram type.

    Args:
        diagram_id: The diagram type ID (e.g., "flowchart", "sequence")

    Returns:
        UpstreamSource with repo, commit, and license info

    Raises:
        KeyError: If diagram_id not found in registry
    """
    if diagram_id not in _DIAGRAM_TYPES:
        msg = f"Diagram type '{diagram_id}' not found in registry"
        raise KeyError(msg)

    # Get the upstream release URI from the diagram type
    graph = Graph()
    registry_path = Path(__file__).parent / "registry.ttl"
    graph.parse(registry_path, format="turtle")

    mer = Namespace("https://seanchatmangpt.github.io/ontology/mermaid#")

    # Find the diagram by its ID
    for diagram in graph.subjects(predicate=mer.diagramId):
        diagram_id_literal = graph.value(diagram, mer.diagramId)
        if str(diagram_id_literal) == diagram_id:
            upstream_release = graph.value(diagram, mer.upstreamRelease)
            if upstream_release:
                source = _UPSTREAM_SOURCES.get(str(upstream_release))
                if source:
                    return UpstreamSource(
                        repo=source["repo"],
                        commit=source["commit"],
                        license=source["license"],
                    )

    # Fallback to default Mermaid 11.16.0 info
    return UpstreamSource(
        repo="https://github.com/mermaid-js/mermaid",
        commit="f0ffb41c1ee1ff667b528e86c3b082249726eeef",
        license="https://opensource.org/license/mit",
    )


def is_python_supported(diagram_id: str) -> bool:
    """Check if a diagram type is supported in Python.

    Args:
        diagram_id: The diagram type ID (e.g., "flowchart", "kanban")

    Returns:
        True if the diagram type has Python implementation, False otherwise

    Raises:
        KeyError: If diagram_id not found in registry
    """
    if diagram_id not in _DIAGRAM_TYPES:
        msg = f"Diagram type '{diagram_id}' not found in registry"
        raise KeyError(msg)

    return diagram_id in _PYTHON_SUPPORTED
