"""GENERATED FILE — do not edit by hand. Regenerate with `ggen sync run`."""

GENERATED_PYTHON_SUPPORTED = frozenset({
    'c4',
    'flowchart',
    'flowchart-v2',
    'flowchart-elk',
    'swimlane',
    'er',
    'gitGraph',
    'gantt',
    'info',
    'pie',
    'quadrantChart',
    'xychart',
    'requirement',
    'sequence',
    'classDiagram',
    'classDiagram-v2',
    'stateDiagram',
    'stateDiagram-v2',
    'journey',
    'timeline',
    'mindmap',
    'kanban',
    'sankey',
    'packet',
    'radar',
    'block',
    'treeView',
    'architecture',
    'eventmodeling',
    'ishikawa',
    'venn',
    'treemap',
    'wardley',
    'cynefin',
    'railroad',
    'railroad-ebnf',
    'railroad-abnf',
    'railroad-peg',
    'zenuml',
})
GENERATED_INTERNAL_SUPPORTED = frozenset({
    'c4',
    'flowchart',
    'flowchart-v2',
    'flowchart-elk',
    'swimlane',
    'er',
    'git',
    'gantt',
    'info',
    'pie',
    'quadrantChart',
    'xychart',
    'requirement',
    'sequence',
    'class',
    'classDiagram-v2',
    'state',
    'stateDiagram-v2',
    'journey',
    'timeline',
    'mindmap',
    'kanban',
    'sankey',
    'packet',
    'radar',
    'block',
    'treeView',
    'architecture',
    'eventmodeling',
    'ishikawa',
    'venn',
    'treemap',
    'wardley',
    'cynefin',
    'railroad',
    'railroad-ebnf',
    'railroad-abnf',
    'railroad-peg',
    'zenuml',
})
SUPPORTED_TYPES = GENERATED_PYTHON_SUPPORTED


def is_supported(diagram_type: str) -> bool:
    """Return whether a canonical or parser-internal type is executable."""
    return diagram_type in GENERATED_PYTHON_SUPPORTED or diagram_type in GENERATED_INTERNAL_SUPPORTED

# Deep domain-specific grammars retained for compatibility. This set is not a
# support ceiling: every catalog type is executable through the universal CST.
STRUCTURED_INTERNAL_TYPES = frozenset({
    "c4", "class", "er", "flowchart", "gantt", "git", "mindmap",
    "pie", "sankey", "sequence", "state",
})
